# application.yml文件中添加如下配置：
spring:
  datasource:
#    url: jdbc:mysql://cdb-5g94sqwc.cd.tencentcdb.com:10048/person?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
#  resources:
#    static-locations: classpath:/static/

logging:
  level:
    main.blog.mapper: trace